# Create build and deploy workflow for deploying .Net 8.0 application to Azure App Service using GitHub Actions 
# Read the Azure subscription from Github Environment variables 
# Get the client credentials from Github secrets
# Use the .Net Github actions to build
# Use the Azure Login action to login to Azure
# Use the Azure Web App action to deploy the application to Azure App Service






